### PR TITLE
Add wrapper for bad pixel mask creation

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR adds a wrapper around the bad pixel generators from flats and from darks, and combines the two into a single bad pixel mask generator. 

I've tweaked some function names as well as the API for the individual bad pixel generators in order to make things a little cleaner. 

Still to do:
- Test the updated code
- Create a mkref_*py function so that mkrefs.py can call this wrapper function
-  Update documentation to reflect this new work
- Create a new mkrefs.cfg file to go with the mkref_*py function

### CODE REVIEW

**Comment by bhilbert4** [comment]
I renamed bad_pixel_mask.py to be badpix_from_flats.py. I thought that made more sense given that the other module is badpix_from_darks.py. Then I created bad_pixel_mask.py as the wrapper function. 

At the moment, it's set up such that it optionally takes a list of flat slope files and a list of dark slope files. If the flats are not provided, it runs only badpix_from_dark.py. If the darks aren't there, it runs only badpix_from_flats.py. If both lists are provided, it runs both routines. Outputs are then combined into a single bad pixel file.

**Comment by jemorrison** [comment]
Ok seems logical.  What about the optional uncal files for darks from flats - the 'dead_flux_check' ?
What did you do about the flag 'LOW_QE' since I do not think that is the in DQ flags the pipeline uses ?

**Comment by bhilbert4** [comment]
The dead_flux_check_files is still an optional input. I basically combined the input lists from badpix_from_flats.py and badpix_from_darks.py into a single (long) list. 

LOW_QE is in the list of bad pixel types that the pipeline uses. Flag value 8192.

**Comment by jemorrison** [comment]
Oh yes I got low_qe and low_ pedistal confused   - I don't think the latter is a DQ flag.
Once you merge this PR I will grab it and test it with MIRI data

**Comment by bhilbert4** [comment]
Ah yes. Low pedestal was something I figured it should search for since we also search for high pedestal. I think the group decided that the low pedestal pixels are still good?

**Comment by jemorrison** [comment]
I am not sure. For MIRI low pedestal has no meaning. What do you mean by high pedestal  - I think
it is terminology difference. How are you planning on putting LOW PEDESTAL as a flag when there is not flag in the DG official flags.

**Comment by bhilbert4** [comment]
At the moment, it looks like low pedestal pixels are flagged with the generic OTHER_BAD_PIXEL flag. High pedestal pixels are those with pedestal values more than N-sigma above the mean pedestal level. The high pedestal pixels are then searched to see if they are RC pixels, and those that are, are flagged as RC.

**Comment by jemorrison** [comment]
Ok this sounds like an good enhancement. When you are ready to merge I will test with MIRI

**Comment by bhilbert4** [comment]
@jemorrison I think this is ready to test now. It works if you call the module yourself, but not yet if you call it through the mkrefs framework. I need to figure out how to get mkrefs to deal with using input files at multiple calibration states. Are you ok with running tests using a copy of my branch? Or should I merge this branch into master and push the mkrefs work into a separate branch?

Here is how I called the module for my testing:

```
from glob import glob
import os
from jwst_reffiles.bad_pixel_mask.bad_pixel_mask import bad_pixels


flat_dir = '/path/to/my/flats/'
flat_files = ['NRCN815A-LIN-5365053444_1_481_SE_2015-12-31T06h21m49_level1bmode_0_ramp_fit.fits',
              'NRCN815A-LIN-5365061037_2_481_SE_2015-12-31T06h56m36_level1bmode_0_ramp_fit.fits',
              'NRCN815A-LIN-5365064512_3_481_SE_2015-12-31T07h31m05_level1bmode_0_ramp_fit.fits',
              'NRCN815A-LIN-5365071954_4_481_SE_2015-12-31T08h05m56_level1bmode_0_ramp_fit.fits',
              'NRCN815A-LIN-5365075436_5_481_SE_2015-12-31T08h40m24_level1bmode_0_ramp_fit.fits',
              'NRCN815A-LIN-5365082921_6_481_SE_2015-12-31T09h15m22_level1bmode_0_ramp_fit.fits']

flat_fluxcheck_files = ['NRCN815A-LIN-5365053444_1_481_SE_2015-12-31T06h21m49_level1bmode_jump.fits',
              'NRCN815A-LIN-5365061037_2_481_SE_2015-12-31T06h56m36_level1bmode_jump.fits',
              'NRCN815A-LIN-5365064512_3_481_SE_2015-12-31T07h31m05_level1bmode_jump.fits',
              'NRCN815A-LIN-5365071954_4_481_SE_2015-12-31T08h05m56_level1bmode_jump.fits',
              'NRCN815A-LIN-5365075436_5_481_SE_2015-12-31T08h40m24_level1bmode_jump.fits',
              'NRCN815A-LIN-5365082921_6_481_SE_2015-12-31T09h15m22_level1bmode_jump.fits']

flat_files = [os.path.join(flat_dir, fname) for fname in flat_files]
flat_fluxcheck_files = [os.path.join(flat_dir, fname) for fname in flat_fluxcheck_files]


dark_files = sorted(glob('/path/to/my/darks/A1/*0_ramp_fit.fits'))
dark_jump_files = sorted(glob('/path/to/my/darks/A1/*jump.fits'))
dark_fitopt_files = sorted(glob('/path/to/my/darks/A1/*fitopt.fits'))

bad_pixels(flat_slope_files=flat_files, dead_search=True, low_qe_and_open_search=True,
               dead_search_type='sigma_rate', flat_mean_sigma_threshold=3, flat_mean_normalization_method='smoothed',
               smoothing_box_width=15, smoothing_type='Box2D', dead_sigma_threshold=5.,  max_dead_norm_signal=None,
               run_dead_flux_check=False, dead_flux_check_files=None, flux_check=45000, max_low_qe_norm_signal=0.5,
               max_open_adj_norm_signal=1.05, manual_flag_file='default', flat_do_not_use=[],
               dark_slope_files=dark_files, dark_uncal_files=None, dark_jump_files=dark_jump_files,
               dark_fitopt_files=dark_fitopt_files,
               dark_stdev_clipping_sigma=5., dark_max_clipping_iters=5,
               dark_noisy_threshold=5, max_saturated_fraction=0.5, max_jump_limit=10, jump_ratio_threshold=5,
               early_cutoff_fraction=0.25, pedestal_sigma_threshold=5, rc_fraction_threshold=0.8, low_pedestal_fraction=0.8,
               high_cr_fraction=0.8,
               flag_values={'hot': ['HOT'], 'rc': ['RC'], 'low_pedestal': ['OTHER_BAD_PIXEL'], 'high_cr': ["TELEGRAPH"]},
               dark_do_not_use=['hot', 'rc', 'low_pedestal', 'high_cr'], plot=False,
               output_file='./test_bpm.fits', author='jwst_reffiles', description='A bad pix mask',
               pedigree='GROUND', useafter='2019-04-01 00:00:00', history='', quality_check=False)
```

**Comment by jemorrison** [comment]
@bhilbert4 can you merge this PR so I can pull it down and test it ?
I just all the python scripts I do not use mkrefs I probably will not be using mkrefs for a long time - after commissioning. I like to have control over how the pipeline is run.

**Comment by bhilbert4** [comment]
Ok, merging now. I'll deal with the mkref_bad_pixel_mask.py edits (and some accompanying edits that will need to be made in mkrefs.py) in a future PR.

**Pull request merged**
