### PR TITLE
Calib prep tests

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR introduces a set of pytests that cover `calib_prep.py`. All tests currently pass for me. In creating the tests, I found one small bug in `calib_prep.py` that was causing the file search function not to work properly. This has been fixed.

I still need to add code to `calib_prep.py` (and then associated tests) to handle the case where the input file is the most appropriate to use as a starting point (regardless of whether the input file is uncal or partially processed. I'll do this as part of a future PR.

@aliciacanipe, can you try running the pytests and make sure they pass for you?

### CODE REVIEW

**Comment by aliciacanipe** [comment]
After I tweaked `completed_steps_test` in `test_calib_prep.py` to match my data (mine had been run through jump and ramp-fit also), the pytests passed. The HTML report outputs for both the failed attempt and the pass are attached. 

`(jwstdev08292018) icecap:jwst_reffiles acanipe$ pytest -v tests/ --html=report.html --self-contained-html --cov=tests --cov-report=html
============================================================================= test session starts =============================================================================
platform darwin -- Python 3.5.5, pytest-3.7.3, py-1.5.4, pluggy-0.7.1 -- /Users/acanipe/miniconda3/envs/jwstdev08292018/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.5.5', 'Packages': {'py': '1.5.4', 'pytest': '3.7.3', 'pluggy': '0.7.1'}, 'Platform': 'Darwin-16.7.0-x86_64-i386-64bit', 'Plugins': {'remotedata': '0.3.0', 'xdist': '1.23.0', 'cov': '2.6.0', 'metadata': '1.7.0', 'html': '1.19.0', 'forked': '0.2'}}
rootdir: /ifs/jwst/wit/witserv/data7/nrc/acanipe/test_mkrefs/jwst_reffiles, inifile:
plugins: xdist-1.23.0, remotedata-0.3.0, metadata-1.7.0, html-1.19.0, forked-0.2, cov-2.6.0
collected 2 items                                                                                                                                                             

tests/test_calib_prep.py::test_calib_prep_steps PASSED                                                                                                                  [ 50%]
tests/test_calib_prep.py::test_pipeline_step_list PASSED                                                                                                                [100%]

------------------------------------- generated html file: /ifs/jwst/wit/witserv/data7/nrc/acanipe/test_mkrefs/jwst_reffiles/report.html --------------------------------------

---------- coverage: platform darwin, python 3.5.5-final-0 -----------
Coverage HTML written to dir htmlcov

========================================================================== 2 passed in 2.73 seconds ===========================================================================`

pytests_failed

pytests_pass

**Comment by bhilbert4** [comment]
Hmmm. Ideally you shouldn't have had to adjust `completed_steps_test`. Is that because `file_for_completed_steps_test.fits` wasn't in the `test_data` subdirectory?

**Comment by aliciacanipe** [comment]
OH, I didn't even see the "test_data" directory when I first cloned your branch because I was looking in the wrong spot, so I was using my own file and running pytest on the parent "tests" directory. If I run pytest from inside "tests", pytest sees the "test_data" directory and all the tests pass. So everything is fine, using both your test data and mine.

**Comment by bhilbert4** [comment]
Ok, great! Thanks!

**Pull request merged**
