### PR TITLE
[WIP] Add module for creating bad pixel mask

### PR DESCRIPTION
**Pull request by bhilbert4**
Still very much a work in progress.

This PR contains code for the creation of the bad pixel mask reference file. This includes pixels that are: 
1) Dead
2) Low QE
3) Open/adjacent to Open

This first commit contains only the code for actually identifying these pixels, but nothing yet for packaging up these pixels into an official reference file. Just creating this PR from the get-go so that @jemorrison can have a look and tell me what I've done wrong so far.

### CODE REVIEW

**Comment by jemorrison** [comment]
also  interesting with the MIRI dead pixels.  I don't think there are actually "dead". When I look at very illuminated data they start out dead and then come to life. maybe these pixels are off scale - below the rail and when they get enough signal they start to detect signal. Not really sure what to do with these pixels now. We should still flag them. They appear dead on low signal data but on high signal data they
start detecting signal at some threshold.

**Comment by bhilbert4** [comment]
Interesting. Well, the MIRI dead pixel search as written at the moment was written with dark data in mind. It is looking for pixels with zero signal. But if you did happen to find high signal data to use, MIRI could always switch to use the dead pixel search that the other instruments are using, with dead defined as signal < (mean - N*sigma).

Let me add in the last bit that combines the different maps and saves them in DMS format using the official DQ values. Then I'll merge. I'm thinking that will make testing against already-existing dq reference files easier.

**Comment by bhilbert4** [comment]
Recent changes:
After all the talk of various instruments wanting to try out certain tests/algorithms, I have removed the instrument-specific if-else blocks from the code, and replaced them with if-else blocks that rely on user inputs. This makes for more inputs, but the code is now more flexible. So if someone down the line wants to try searching for dead pixels by finding pixels with 0 signal in a ramp using NIRCam data, they can easily do that without there having to be changes to the code.

I also started creating the code necessary to plug this module into mkrefs, but I realized that mkrefs doesn't currently support providing a large stack of flats or darks to the plugged in modules. Adding this is on @arminrest 's To Do list. So at the moment, you can test the code, but you'll have to run it as a standalone module, outside of mkrefs.py. 

Lingering issues that need to be fixed:
1. The REFERENCE_PIXEL value in dq_def should be 2**31, but for some reason once this value is input into the MaskModel instance, it is being changed to -2**31. I've asked Howard, and this appears to be a bug in the pipeline that will be fixed soon.
2. In the case where the MIRI dead pixel search is done (i.e. looking for pixels with exactly 0 signal in one group of each integration), the groups are then what are used in the other searches. So a normalized mean group is created, and this is what goes into the low QE/open pixel searches. Is this what MIRI wants? Or should MIRI also use slope images for those latter tests? If so there would have to be two sets of inputs for MIRI.
3. Need to add more tests
4. Need to add documentation page for ReadTheDocs

@jemorrison, I've tested the code using the "MIRI" dead pixel search (looking for pixels with zero signal), and everything worked (except for issue 1 above). I don't have good slope images from flats at the moment for testing the other methods. I'll work on that later this week. But in the meantime, for your testing, you want me to merge this PR?

**Comment by jemorrison** [comment]
Yes go ahead and merge this PR and I am going to start using it. 
Do you have an example of how to call it  - I need a mkrefs.cfg and will mkref.py call the dq flagging steps ?

**Comment by jemorrison** [comment]
Ok I just re-read your comments. I have to run the code as a stand alone. Outside of mkref.py

**Comment by bhilbert4** [comment]
Yeah, for the moment it's not integrated with mkrefs.py. I'm trying to look up how to get Read the Docs to automatically read the docstrings and create pages for them. In the meantime, check the docstring for the `find_bad_pix` function in bad_pixel_mask.py, and let me know if you have any questions.

**Pull request merged**
