### PR TITLE
Correct output names

### PR DESCRIPTION
**Pull request by bhilbert4**
These edits allow all of the pytests to pass. I tweaked the constructed output filenames (for some reason I had all filenames prior to ramp-fitting ending in "_ramp.fits". I removed that. Hopefully I didn't put that there to deal with the pipeline's rules for stripping and replacing suffix pieces.)

### CODE REVIEW

**Comment by bhilbert4** [comment]
Note that at the moment, our pipeline output files do not follow the default behavior for names.

For a file where dq_init, saturation, and superbias subtraction is done, the pipeline by default would create:

filename_superbias.fits

In `calib_prep.py` we instead save the file as:

filename_dq_init_saturation_superbias.fits

This is so that we can easily tell what pipeline steps have been run on a given file without opening it. It also gives us a way to differentiate between files that have been run up to the same point in the pipeline, but in one case certain steps were skipped. With the default pipeline naming convention, the filenames would be identical in that example.

**Comment by bhilbert4** [comment]
I also added output_dir information to the pipeline calls.

**Comment by bhilbert4** [comment]
@aliciacanipe, there's not much of a review needed here I don't think. Could you just give it a quick glance and make sure there's nothing obviously wrong?

**Comment by aliciacanipe** [comment]
I started to look at your code and then went down a rabbit hole of how the pipeline decides what the suffix is for output files that get saved. It seems like the strun method and the ipython methods attach a different default suffix? For instance, sometimes "dq_init" gets added and sometimes "dqinitstep" gets added. If you are specifying the suffix in the code though, I guess this isn't really an issue for mkrefs. Anyway, I'll review the code real quick.

**Comment by bhilbert4** [comment]
I'm not sure if the suffixes to depend on calling method. They might. What bothers me is that if your file happens to end in one of the magic suffixes, the pipeline will strip that suffix off your file and replace it when running the next pipeline step.

That's why these days I like to use the `suffix` keyword, so that I can specify exactly what the output filename will be.

**Review by aliciacanipe — COMMENTED** [review]
test_calib_prep is failing for me on the strun_command_test. It looks like the constructed commands use the "suffix" option but the truths still use the "output_file" option. I think ramp_fitting in the truths should also be changed to ramp_fit, right?

**Comment by bhilbert4** [comment]
Ah yes. I forgot to update the test. I'll do that in a bit.

**Comment by arminrest** [comment]
Looks all good!

**Comment by bhilbert4** [comment]
Something very strange happened to this PR. @arminrest, `Close` is different than `Merge`. :) I reopened the PR, but there were missing commits. I updated, but now Travis is failing because the tests go more than 10 minutes with no response. One of them also fails because `nbsphinx` is not installed, which it was yesterday.

Others reported problems with jupyter notebooks on github this morning. I wonder if this is related.

**Comment by arminrest** [comment]
lol, oh boy, looks like I messed things up. I was in a hurry to get 
home, and I just wanted to get the latest version on my laptop... let me 
know when you have fixed it....

**Comment by bhilbert4** [comment]
Ok, I added `nbsphinx` to the dependency list in the .travis.yml file, and all tests are now passing. Turns out the setup test had been failing all along when it couldn't find `nbsphinx`, but was reporting that it had passed for some reason. 

Anyway, the tests are now all passing for real, and the code updates look to be behaving well, so I'm going to merge this.

@arminrest be sure to pull this version of the code before starting any tests.

**Pull request merged**
