### PR TITLE
Include sigma-clipping in mean calc for noisy search

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR changes the code such that sigma-clipping is used when computing the mean and standard deviation of the standard deviation values across the input slope images.

### CODE REVIEW

**Comment by bhilbert4** [comment]
@KevinVolkSTScI, is this the change you envisioned? The script was already using scipy's sigma clipping function, so I thought it would be easiest to start by using that again.

**Comment by KevinVolkSTScI** [comment]
This is similar to what I was doing, but I prefer not to use sigmaclip because there is no control over the number of iterations that it does and the results can become very sensitive to noise in cases where the main distribution is not Gaussian.  I would just have to see what the results look like compared to the other cases that I coded in for the specific example of NIRISS darks.  It may not make a big difference in practical terms.

**Comment by bhilbert4** [comment]
@KevinVolkSTScI I just updated the code to use astropy's sigma_clip. The maximum number of iterations is now a user-settable parameter.

**Comment by KevinVolkSTScI** [comment]
I took a look at the code changes and it all looks good.  I have to test it and see what the results are, but I may not have time this week.

**Comment by KevinVolkSTScI** [comment]
I made a trial run with the changes and it flagged 130000 noisy pixels.  That is roughly similar to what I got myself.  So it looks like it is working, although I need to do some analysis on the results when I have time.

**Comment by bhilbert4** [comment]
I'm glad the results are more in agreement than before. I'm going to merge this so that others can test with the sigma clipping as well.

**Pull request merged**
