### PR TITLE
Add logging

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR introduces code to enable logging in the `jwst_reffiles` package. Currently logging covers only `mkrefs.py, mkref.py, and pipeline/calib_prep,.py`. Logging for modules that will be plugged in will be captured in different files. The names of these files are present in the log file created by these code changes.

I have added the minimum logging level for 1) the output log file and 2) messages to the screen, as user inputs. This way users can customize the logs without having to update the code itself. Both parameters default to using INFO as the minimum log level. Options are 'critical', 'warning', 'info',' and 'debug'. 

To set the levels:
`mkrefs.py -vvv --cfgfile mkrefs.cfg example_readnoise_module My_dir/darks/*DARK-600*level1b_Sept2018_uncal.fits My_dir/A1/F150W2/NRCN815A-LIN-53650[5678]*uncal.fits --logFileLevel info --logScreenLevel warning`

The output log file is written to a directory specified by the runID, and includes a timestamp in the filename, for uniqueness.

### CODE REVIEW

**Comment by bhilbert4** [comment]
@bsunnquist or @aliciacanipe, do you have a few minutes to test this at some point? I think a successful test would be that a logfile is created and that it's populated with messages of the appropriate severity level. And that the permissions are such that the logfile is world readable.

To call, use the same command that you have used in the past, but tack on two more keywords:
`--logFileLevel info --logScreenLevel warning`. The values of the keywords are the minimum severity levels that should appear in the log file and on the screen, respectively. Allowed values are 'debug', 'info', 'warning', 'error', and 'critical'. (I don't think i have any critical messages in the code.)

**Comment by bsunnquist** [comment]
I should be able to test this later this week

**Comment by bsunnquist** [comment]
I tried running this, but received an AttributeError: 'mkrefsclass' object has no attribute 'logger' (see attached). I'm using an old cfg file - do these have to be updated with more information for these new logging features to work?

screen shot 2019-02-27 at 9 01 48 am

**Comment by bsunnquist** [comment]
That fixed it, but now I'm receiving a permission error (see attached). I'm running in the wit shared central storage directory, and I think you're running on your computer, so maybe that's the issue?

screen shot 2019-02-27 at 3 40 28 pm

Here are what the permissions look like on the file:
screen shot 2019-02-27 at 3 46 13 pm

**Comment by bhilbert4** [comment]
Hmmm, I was afraid of this. Right now I have permissions being set such that the log file is readable and writable by the owner and the group. But when I ran tests, the files I created were under the 'staff' group. It looks like yours are under STSCI/wit. Maybe I should just open up permissions to make the files readable and writable by everyone. Eventually lots of people could  be using this package, and I have no idea what other groups could be used.

**Comment by bhilbert4** [comment]
OK, now the log files should be writable.

**Comment by bsunnquist** [comment]
Yeah, there are a lot of groups, so that makes sense. Just ran it again and got this attribute error:

screen shot 2019-02-27 at 3 55 25 pm

**Comment by bhilbert4** [comment]
Oops. I forgot to prepend an 'S_' to those. I just pushed an updated copy.

**Comment by bsunnquist** [comment]
Getting that same permission error again, looks like the permissions haven't changed on that file
screen shot 2019-02-27 at 4 01 46 pm

**Comment by bsunnquist** [comment]
Ah, wait, I started fresh (deleted the test1 directory), and the log files permissions changed correctly (read and write for everyone), but I still got this error

screen shot 2019-02-27 at 4 03 45 pm

**Comment by bhilbert4** [comment]
Looks like it doesn't want to let you change the group associated with the file. I'll have to think about why that might be.

**Comment by bhilbert4** [comment]
Thinking about it last night, it seems like setting all files to have the same Unix group doesn't really help us much. So I turned off that command entirely. I switched the default permissions such that any files you create should be readable and writable by you, and group readable.

**Comment by bsunnquist** [comment]
Looks good! I just re-ran with `--logFileLevel info` and the log file is generated with INFO, WARNING, and ERROR entries (see attached). There are some warnings/errors in there e.g. "ERROR - WARNING: It seems like the filename...is not a fits file" and "WARNING - ERROR: file...did not get created with strun command!". Though the output readnoise fits files look good, and the log file permissions are correct (rw for me, r for group, no access for everyone else).

[mkrefs_2019-02-28-14-46.log](https://github.com/spacetelescope/jwst_reffiles/files/2916906/mkrefs_2019-02-28-14-46.log)

**Comment by bhilbert4** [comment]
Excellent thanks! I clarified those ERROR - WARNING and WARNING - ERROR messages. Do you think this is ready to merge?

**Pull request merged**
