### PR TITLE
added normalization by 2D fit and flux_check for pixels saturating 

### PR DESCRIPTION
**Pull request by jemorrison**
Added normalization method  = fit2d
A 2d fit is performed on the average rate image to remove the illumination pattern. For MIRI is is preferred to box car smoothing because the box car smoothing - smooths the clusters of hot pixels to surrounding pixels.
In addition a flux_check is performed if flux_check = list_of_ramp_images. The average of the last 4 frames for all the integrations all the exposures is determined. This image is used with the dead_map. If a pixel in the initial dead_map has a average_group value > tolerance then it is removed from the dead pixel map. This check is to remove hot pixels that saturate on the first frame and produce a rate value close to 0.

### CODE REVIEW

**Comment by bhilbert4** [comment]
Looks good to me. I think that replacing the zero_signal option with this new flux_check makes sense. If someone wanted to use use zero_signal, they could just run flux_check using a limit of 0, right? This seems to me like it's ready to merge.

**Comment by bhilbert4** [comment]
Do you want to merge this now, or add the sigma-clipped box smoothing that was talked about at the meeting?

**Comment by jemorrison** [comment]
I want to add the sigma-clipped box smoothing first. I will start working on that now

**Comment by jemorrison** [comment]
for bad_pixel_mask.py  this recent push took out fitting the rate image with a 2D fit and instead added a smoothing filter using median filtering using scipy median_filter.  I left in the flux_check method (check if a flagged dead pixel should be removed from dead pixel type because it is a saturated pixel). The details of how this are done could be changed I just took a first stab at it. 

for badpix_from_darks.py
I had to make some changes to get the code to run. I also moved where counter is getting incremented. Counter is the number of files so I also changed how different arrays are updated in each integration. Since the number of integrations/exposure could vary for each exposure it was
easier to keep counter referencing file# and add total_ints as an additional counter.

**Comment by jemorrison** [comment]
can I merge this PR ?
I am going to work next on understanding the lack of bad pixels found using the jump detection. So I might have a new set of changes.

**Comment by bhilbert4** [comment]
Sure, looks good to me.

**Pull request merged**
